apiVersion: v1
kind: Service
metadata:
  name: myworker
  labels:
    app: myworker
spec:
  ports:
  - port: 8000  # TODO expose this as a worker management
    name: http
  selector:
    app: myworker
  type: NodePort # Or LoadBalancer in production w/ proper security
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myworker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myworker
    spec:
      containers:
      - name: myworker
        image: matibek/mysite
        imagePullPolicy: Always # For debuging
        env:
        - name: WORKER
          value: "true"
